### ISSUE TITLE
rule internal sets appear broken

### ISSUE THREAD

**Issue by commiebstrd** [Natolumin/language-nftables#3]
Not entirely sure if this is the `{dhcp, dhcp6}` set or dual udp dport/sport, but removing either results in no change and removing the line entirely causes the remaining rules to parse correctly. Wasn't sure with all the recent changes if this might already be fixed somewhere? Note the third line of ext-out.

![github doesnt like my png](http://i.imgur.com/MWDBmtv.png)

**Comment by Natolumin** [comment]
Yeah, I had a rewrite pending that you basically prodded me into actually publishing. The previous version of the published plugin was quite broken, but I didn't know I actually had users so I wasn't fixing it.

Could you copy the ruleset you screenshotted here so that I can add it to my test file and check if this still happens on master ?
(I published 0.3.0 earlier today that you might be able to upgrade to as well)

**Comment by Natolumin** [comment]
Found it, it tries to parse dhcpv6-server as a range and the range match is a bit too greedy, so it interprets the rest of the line as a range element

For now I'll make the range stop on delimiters such as , and }, but there is probably a better solution so I'm keeping this open for now.

**Comment by commiebstrd** [comment]
Busy week over here, looks like that fixed it! I'll want to clean some things up but could submit a few test files if you'd like. Anything in particular you are looking for? I tend not to use more complex logic until rules are set in stone and don't require counters or individual logging, since some of the granularity is lost.

![still not sure whats wrong with screenshots...](http://i.imgur.com/Ix7Y1dQ.png)

Ha, sorry about prodding you into releasing! I just stumbled upon it when working out an issue with nftables not loading this particular config, after a new non-hook chain. In the future I'd suggest committing to a maintenance branch as you're working. Would have been more than happy to pull your unreleased code and submit patches there also. I've got a few atom things in the works as well, pulling unreleased changes is totally ok! Otherwise work so far look great and seem much more stable!

**Comment by Natolumin** [comment]
Not looking for anything in particular (I have a good set already), it's just that pasting images in the issue makes it easy to see the coloring but hard to copy/paste your rules to check that I fixed the bug properly, so please post both the image and the text inside when possible.

I haven't commited the files I use to test syntax classification, but if you want to contribute some (especially things that you find are or were broken) I'll add mine as well.

**Comment by commiebstrd** [comment]
Perfect can do and totally see your point on wanting flat files too. Is there a mapping you are using from the nftables config or types to atom element tags? Seems like `accept|drop|log` would want to be differentiated from `counter|comment`, unsure of which tag they should have though. :)

**Comment by Natolumin** [comment]
let's move the tag naming discussion to #5 
The workaround-solution for this is not as bad as some of the other stuff in the grammar, so I'll mark this closed for now.
